# Generated by Django 5.2.17 on 2026-09-28 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('folio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('COBRADA', 'Cobrada'), ('CANCELADA', 'Cancelada')], default='EN_CURSO', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='accounts.negocio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('negocio', 'folio'), name='folio_unico_por_negocio'),
        ),
    ]
