# Generated by Django 5.2.17 on 2026-09-28 04:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teléfono celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_tienda', models.CharField(max_length=150, verbose_name='Nombre de tu tienda')),
                ('alcaldia', models.CharField(blank=True, choices=[('IZTAPALAPA', 'Iztapalapa'), ('GAM', 'Gustavo A. Madero'), ('ALVARO_OBREGON', 'Álvaro Obregón'), ('TLALPAN', 'Tlalpan'), ('COYOACAN', 'Coyoacán'), ('XOCHIMILCO', 'Xochimilco'), ('OTRA', 'Otra')], max_length=30, verbose_name='Alcaldía')),
                ('anios_operacion', models.CharField(choices=[('MENOS_DE_1', 'Menos de 1 año'), ('DE_1_A_3', '1 a 3 años'), ('DE_3_A_10', '3 a 10 años'), ('MAS_DE_10', 'Más de 10 años')], default='DE_3_A_10', max_length=20, verbose_name='Años de operación')),
                ('regimen_resico', models.BooleanField(default=True, verbose_name='Régimen RESICO')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
